# starship.toml - Starship Prompt Configuration
# ------------------------------------------------------------
# æ­¤æ–‡ä»¶ç”¨äºè‡ªå®šä¹‰ Starship æç¤ºç¬¦çš„å¤–è§‚å’Œè¡Œä¸ºã€‚"$schema" = 'https://starship.rs/config-schema.json'

# $username\  î‚¶î‚´î‚° â˜•ï¸ ó±— îŸ…

format = """\
($directory)\
$os\
$git_branch\
$git_status\
 ğŸ€\
$fill\
$cmd_duration\
$c\
$bun\
$nodejs\
$rust\
$golang\
$php\
$java\
$kotlin\
$python\
$conda\
$docker_context\
$zig\
$time\
$battery\
$line_break$character\
"""

add_newline = true
command_timeout = 3600000
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[line_break]
disabled = false

[fill]
symbol = ' '

[character]
disabled = false
success_symbol = "[ó±— ](fg:green)"
error_symbol = "[ó±— ](fg:red)"
vimcmd_symbol = "[îŸ… ](bold red)"
vimcmd_replace_one_symbol = "[R](bold peach)"
vimcmd_visual_symbol = "[V](bold mauve)"

[username]
disabled = false
show_always = false
style_user = 'bold blue'
style_root = 'bold red'
format = '[ó±— $user](fg:$style) '

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 5
style = "fg:blue"
read_only_style = "fg:blue"
before_repo_root_style = "fg:blue"
truncation_symbol = "â€¦/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[cmd_duration]
format = " [t.$duration]($style) "
style = "fg:surface1"
min_time = 500

[git_branch]
symbol = "ï˜"
format = " ğŸŒ±  [$symbol $branch]($style) "
style = "bold fg:mauve"

[git_status]
format = '[($all_status$ahead_behind )]($style)'
style = "fg:text"

[python]
disabled = false
symbol = "î˜†"
format = "[ $symbol$pyenv_prefix($version)( $virtualenv)](fg:peach)"
version_format = "$raw"

[java]
disabled = false
symbol = "î‰–"
format = '[[ $symbol ($version) ](fg:red)]($style)'
version_format = "$raw"

[kotlin]
symbol = "î˜´"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
disabled = false
symbol = "î˜ "
format = '[[ $symbol ($version) ](fg:blue)]($style)'
version_format = "$raw"

[zig]
disabled = false
format = '[[ $symbol ($version) ](fg:peach)]($style)'
version_format = "$raw"

[bun]
disabled = false
version_format = "$raw"
format = '[[ $symbol ($version) ](fg:text)]($style)'

[nodejs]
symbol = "îœ˜"
format = '[[ $symbol ($version) ](fg:green)]($style)'

[rust]
symbol = "î¨"
format = '[[ $symbol ($version) ](fg:red)]($style)'

[golang]
symbol = "î˜§"
format = '[[ $symbol ($version) ](fg:teal)]($style)'

[php]
symbol = "î˜ˆ"
format = '[[ $symbol ($version) ](fg:peach)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[docker_context]
disabled = true

[time]
disabled = false
time_format = "%R"
format = '[[   ïº $time ](fg:subtext0)]($style)'

[battery]
disabled = false
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó°‚ƒ "
unknown_symbol = "ó°½ "
empty_symbol = "ó°‚ "
format = "[$symbol$percentage]($style) "
[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'
[[battery.display]] # 'bold yellow' style and discharging_symbol when capacity is between 10% and 30%
threshold = 30
style = 'bold yellow'
